# Generated by Django 5.0.6 on 2024-05-08 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240508_1456'),
    ]

    operations = [
    ]
