# Generated by Django 5.0.6 on 2024-05-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240508_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
